import { useState, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, FileImage, FileText, Check } from "lucide-react";
import { GlassCard } from "./ui/GlassCard";
import { Button3D } from "./ui/Button3D";

interface Agent {
    id?: string;
    role: string;
    description?: string;
    status?: string;
}

interface Workflow {
    id: string;
    name: string;
    description?: string;
    agents?: Agent[];
    steps?: string[];
}

interface WorkflowExportModalProps {
    workflow: Workflow;
    isOpen: boolean;
    onClose: () => void;
}

// Agent icon color mapping
const getAgentColor = (role: string): string => {
    const roleLower = role.toLowerCase();
    if (roleLower.includes('email')) return '#f97316';
    if (roleLower.includes('data')) return '#22c55e';
    if (roleLower.includes('document') || roleLower.includes('ocr')) return '#3b82f6';
    if (roleLower.includes('api') || roleLower.includes('orchestrator')) return '#8b5cf6';
    if (roleLower.includes('notification')) return '#f59e0b';
    if (roleLower.includes('security')) return '#ef4444';
    if (roleLower.includes('report')) return '#06b6d4';
    return '#64748b';
};

export default function WorkflowExportModal({ workflow, isOpen, onClose }: WorkflowExportModalProps) {
    const [isExporting, setIsExporting] = useState(false);
    const [exportSuccess, setExportSuccess] = useState(false);
    const svgRef = useRef<SVGSVGElement>(null);

    const agents = workflow.agents || [];
    const steps = workflow.steps || [];

    // Download as PNG
    const handleDownloadPNG = useCallback(async () => {
        if (!svgRef.current) return;

        setIsExporting(true);
        try {
            const svgElement = svgRef.current;
            const svgData = new XMLSerializer().serializeToString(svgElement);
            const canvas = document.createElement('canvas');
            const ctx = canvas.getContext('2d');
            const img = new Image();

            canvas.width = 1200;
            canvas.height = 800;

            img.onload = () => {
                if (ctx) {
                    ctx.fillStyle = '#1a1a1a';
                    ctx.fillRect(0, 0, canvas.width, canvas.height);
                    ctx.drawImage(img, 0, 0);

                    const link = document.createElement('a');
                    link.download = `${workflow.name.replace(/\s+/g, '_')}_flowchart.png`;
                    link.href = canvas.toDataURL('image/png');
                    link.click();

                    setExportSuccess(true);
                    setTimeout(() => setExportSuccess(false), 2000);
                }
                setIsExporting(false);
            };

            img.src = 'data:image/svg+xml;base64,' + btoa(unescape(encodeURIComponent(svgData)));
        } catch (error) {
            console.error('Export failed:', error);
            setIsExporting(false);
        }
    }, [workflow.name]);

    // Download as text summary
    const handleDownloadSummary = useCallback(() => {
        const summary = `
WORKFLOW: ${workflow.name}
${'='.repeat(50)}

Description: ${workflow.description || 'No description'}

AGENTS (${agents.length}):
${agents.map((a, i) => `  ${i + 1}. ${a.role} - ${a.status || 'Pending'}`).join('\n')}

STEPS (${steps.length}):
${steps.map((s, i) => `  ${i + 1}. ${s}`).join('\n')}

Generated by CogniFloe AI Workflow Automation
        `.trim();

        const blob = new Blob([summary], { type: 'text/plain' });
        const link = document.createElement('a');
        link.download = `${workflow.name.replace(/\s+/g, '_')}_summary.txt`;
        link.href = URL.createObjectURL(blob);
        link.click();

        setExportSuccess(true);
        setTimeout(() => setExportSuccess(false), 2000);
    }, [workflow, agents, steps]);

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-[100] bg-black/70 backdrop-blur-sm flex items-center justify-center p-4"
                onClick={onClose}
            >
                <motion.div
                    initial={{ scale: 0.9, opacity: 0 }}
                    animate={{ scale: 1, opacity: 1 }}
                    exit={{ scale: 0.9, opacity: 0 }}
                    onClick={(e) => e.stopPropagation()}
                    className="w-full max-w-4xl max-h-[90vh] overflow-auto"
                >
                    <GlassCard className="p-6 space-y-6">
                        {/* Header */}
                        <div className="flex items-center justify-between">
                            <div>
                                <h2 className="text-xl font-bold text-foreground">Export Workflow</h2>
                                <p className="text-sm text-muted-foreground">{workflow.name}</p>
                            </div>
                            <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-lg">
                                <X className="w-5 h-5 text-muted-foreground" />
                            </button>
                        </div>

                        {/* Flowchart Preview */}
                        <div className="bg-stone-900 rounded-xl p-6 border border-white/10">
                            <svg
                                ref={svgRef}
                                viewBox="0 0 1200 600"
                                className="w-full h-auto"
                                style={{ minHeight: '400px' }}
                            >
                                {/* Background gradient */}
                                <defs>
                                    <linearGradient id="bgGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                                        <stop offset="0%" stopColor="#1a1a1a" />
                                        <stop offset="100%" stopColor="#2d2d2d" />
                                    </linearGradient>
                                    <marker
                                        id="exportArrow"
                                        markerWidth="10"
                                        markerHeight="7"
                                        refX="9"
                                        refY="3.5"
                                        orient="auto"
                                    >
                                        <polygon points="0 0, 10 3.5, 0 7" fill="#f97316" />
                                    </marker>
                                </defs>

                                <rect width="1200" height="600" fill="url(#bgGrad)" />

                                {/* Title */}
                                <text x="600" y="50" textAnchor="middle" fill="white" fontSize="24" fontWeight="bold">
                                    {workflow.name}
                                </text>
                                <text x="600" y="75" textAnchor="middle" fill="#888" fontSize="14">
                                    {workflow.description || 'Automated Workflow'}
                                </text>

                                {/* Agent nodes */}
                                {agents.length > 0 ? (
                                    agents.map((agent, i) => {
                                        const totalAgents = agents.length;
                                        const nodeWidth = 140;
                                        const nodeHeight = 80;
                                        const totalWidth = totalAgents * nodeWidth + (totalAgents - 1) * 60;
                                        const startX = (1200 - totalWidth) / 2;
                                        const x = startX + i * (nodeWidth + 60);
                                        const y = 150;
                                        const color = getAgentColor(agent.role);

                                        return (
                                            <g key={agent.id || i}>
                                                {/* Connection line to next agent */}
                                                {i < agents.length - 1 && (
                                                    <motion.line
                                                        x1={x + nodeWidth}
                                                        y1={y + nodeHeight / 2}
                                                        x2={x + nodeWidth + 60}
                                                        y2={y + nodeHeight / 2}
                                                        stroke="#f97316"
                                                        strokeWidth="2"
                                                        markerEnd="url(#exportArrow)"
                                                        initial={{ pathLength: 0 }}
                                                        animate={{ pathLength: 1 }}
                                                        transition={{ delay: i * 0.2, duration: 0.5 }}
                                                    />
                                                )}

                                                {/* Node background */}
                                                <motion.rect
                                                    x={x}
                                                    y={y}
                                                    width={nodeWidth}
                                                    height={nodeHeight}
                                                    rx="12"
                                                    fill={color + '20'}
                                                    stroke={color}
                                                    strokeWidth="2"
                                                    initial={{ scale: 0, opacity: 0 }}
                                                    animate={{ scale: 1, opacity: 1 }}
                                                    transition={{ delay: i * 0.15 }}
                                                />

                                                {/* Agent icon circle */}
                                                <motion.circle
                                                    cx={x + nodeWidth / 2}
                                                    cy={y + 25}
                                                    r="12"
                                                    fill={color}
                                                    initial={{ scale: 0 }}
                                                    animate={{ scale: 1 }}
                                                    transition={{ delay: i * 0.15 + 0.1 }}
                                                />

                                                {/* Agent role text */}
                                                <text
                                                    x={x + nodeWidth / 2}
                                                    y={y + 55}
                                                    textAnchor="middle"
                                                    fill="white"
                                                    fontSize="10"
                                                    fontWeight="500"
                                                >
                                                    {agent.role.length > 18 ? agent.role.slice(0, 16) + '...' : agent.role}
                                                </text>

                                                {/* Status badge */}
                                                <text
                                                    x={x + nodeWidth / 2}
                                                    y={y + 70}
                                                    textAnchor="middle"
                                                    fill="#888"
                                                    fontSize="8"
                                                >
                                                    {agent.status || 'Pending'}
                                                </text>
                                            </g>
                                        );
                                    })
                                ) : (
                                    <text x="600" y="200" textAnchor="middle" fill="#888" fontSize="16">
                                        No agents configured
                                    </text>
                                )}

                                {/* Steps section */}
                                <text x="100" y="300" fill="#888" fontSize="14" fontWeight="bold">
                                    WORKFLOW STEPS
                                </text>
                                <line x1="100" y1="310" x2="1100" y2="310" stroke="#333" strokeWidth="1" />

                                {steps.slice(0, 8).map((step, i) => (
                                    <g key={i}>
                                        <motion.circle
                                            cx="120"
                                            cy={340 + i * 30}
                                            r="8"
                                            fill="#f97316"
                                            initial={{ scale: 0 }}
                                            animate={{ scale: 1 }}
                                            transition={{ delay: 0.5 + i * 0.1 }}
                                        />
                                        <motion.text
                                            x="140"
                                            y={345 + i * 30}
                                            fill="#ccc"
                                            fontSize="12"
                                            initial={{ opacity: 0, x: -10 }}
                                            animate={{ opacity: 1, x: 0 }}
                                            transition={{ delay: 0.5 + i * 0.1 }}
                                        >
                                            {step.length > 80 ? step.slice(0, 77) + '...' : step}
                                        </motion.text>
                                    </g>
                                ))}

                                {steps.length > 8 && (
                                    <text x="140" y={345 + 8 * 30} fill="#888" fontSize="11">
                                        ... and {steps.length - 8} more steps
                                    </text>
                                )}

                                {/* Footer */}
                                <text x="600" y="580" textAnchor="middle" fill="#555" fontSize="10">
                                    Generated by CogniFloe • AI Workflow Automation
                                </text>
                            </svg>
                        </div>

                        {/* Export buttons */}
                        <div className="flex gap-4 justify-end">
                            {exportSuccess && (
                                <motion.div
                                    initial={{ opacity: 0, x: -10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    className="flex items-center gap-2 text-forest-500"
                                >
                                    <Check className="w-4 h-4" />
                                    <span className="text-sm">Downloaded!</span>
                                </motion.div>
                            )}
                            <Button3D
                                variant="ghost"
                                size="sm"
                                onClick={handleDownloadSummary}
                                leftIcon={<FileText className="w-4 h-4" />}
                            >
                                Download Summary
                            </Button3D>
                            <Button3D
                                variant="organic"
                                size="sm"
                                onClick={handleDownloadPNG}
                                isLoading={isExporting}
                                leftIcon={<FileImage className="w-4 h-4" />}
                            >
                                Download PNG
                            </Button3D>
                        </div>
                    </GlassCard>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}
